<?php

return [
    [
        'id' => 1,
        'user_id' => 1,
        'hostname' => 'DATA-NET', 
        'password' => word_pass(),
        'org' => 'INTERNATIONAL DATA MACHINES CORP. (IDM) [ONLINE]',
        'location' => 'ARMON, NEW YORK, USA',
        'welcome' => 'WELCOME TO IDM CORP.',
        'notes' => 'SYSADMIN: ADMIN@DATA-NET',
        'os' => 'U/DOS V1.10',
        'ip' => random_ip(),
        'network' => 1,
        'level_id' => 1,
        'created_at' => timestamp("1911-06-16 06:30:00", true)
    ],
    [
        'id' => 2,
        'user_id' => 1,
        'hostname' => 'ROBCOM-NET', 
        'password' => word_pass(),
        'org' => 'ROBOT & COMPUTER IND. (RCI) [ONLINE]',
        'location' => 'ALBUQUERQUE, NEW MEXICO, USA',
        'welcome' => 'WELCOME TO ROBCOM CORP.',
        'notes' => 'SYSADMIN: ADMIN@ROBCOM-NET',
        'os' => 'U/DOS V1.10',
        'ip' => random_ip(),
        'network' => 1,
        'level_id' => 2,
        'created_at' => timestamp("1942-06-25 06:30:00", true)
    ],
    [
        'id' => 3,
        'user_id' => 1,
        'hostname' => 'GEC-NET', 
        'password' => random_pass(),
        'org' => 'GENERAL ENERGY CORP. (GEC) [ENCRYPTED]',
        'location' => 'SAN RAMON, CALIFORNIA, USA',
        'welcome' => 'WELCOME TO GEC CORP.',
        'notes' => 'SYSADMIN: ADMIN@GEC-NET',
        'os' => 'U/DOS V3.0',
        'ip' => random_ip(),
        'network' => 1,
        'level_id' => 3,
        'created_at' => timestamp("1892-04-30 06:30:00", true)
    ],
    [
        'id' => 4,
        'user_id' => 1,
        'hostname' => 'COPSEC-NET', 
        'password' => random_pass(),
        'org' => 'CORPORATE SECURITY CORP. (CSC) [ENCRYPTED]',
        'location' => 'STAMFORD, CONNECTICUT, USA',
        'welcome' => 'WELCOME TO COP-SEC CORP.',
        'notes' => 'SYSADMIN: ADMIN@COPSEC-NET',
        'os' => 'U/DOS V3.0',
        'ip' => random_ip(),
        'network' => 1,
        'level_id' => 3,
        'created_at' => timestamp("1931-10-30 06:30:00", true)
    ],
    [
        'id' => 5,
        'user_id' => 1,
        'hostname' => 'DEFCOM-NET', 
        'password' => random_pass(),
        'org' => 'DEFENSE & COMMUNICATIONS CORP. (DFC) [LOCKED]',
        'location' => 'LOS ANGELES, CALIFORNIA, USA',
        'welcome' => 'WELCOME TO DEF-COM CORP.',
        'notes' => 'SYSADMIN: ADMIN@DEFCOM-NET',
        'os' => 'U/DOS V4.0',
        'ip' => random_ip(),
        'network' => 1,
        'level_id' => 4,
        'created_at' => timestamp("1958-10-30 06:30:00", true)
    ],
    [
        'id' => 6,
        'user_id' => 1,
        'hostname' => 'SATCOM-NET', 
        'password' => random_pass(),
        'org' => 'SPACESTATION COMMUNICATIONS CORP. (STC) [LOCKED]',
        'location' => 'HAWTHORNE, CALIFORNIA, USA',
        'welcome' => 'WELCOME TO SAT-COM CORP.',
        'notes' => 'SYSADMIN: ADMIN@SATCOM-NET',
        'os' => 'U/DOS V4.0',
        'ip' => random_ip(),
        'network' => 1,
        'level_id' => 4,
        'created_at' => timestamp("1958-04-14 06:30:00", true)
    ],
    [
        'id' => 7,
        'user_id' => 1,
        'hostname' => 'NEURAL-NET', 
        'password' => random_pass(),
        'org' => 'CONTROL & AUTOMATION IND. (CAI) [UNKNOWN]',
        'location' => 'CAMBRIDGE, MASSACHUSETTS, USA',
        'welcome' => 'WELCOME TO CAI CORP.',
        'notes' => 'SYSADMIN: ADMIN@NEURAL-NET',
        'os' => 'CAX/MUDOS V1.4',
        'ip' => random_ip(),
        'network' => 1,
        'level_id' => 5,
        'created_at' => timestamp("1978-03-09 06:30:00", true)
    ],
        [
        'id' => 8,
        'user_id' => 1,
        'hostname' => 'SYSCORP-NET', 
        'password' => random_pass(),
        'org' => 'SYSTEMS CORP. SYNDICATE (SCS) [UNKNOWN]',
        'location' => '[REDACTED]',
        'welcome' => 'WELCOME TO THE SYNDICATE.',
        'notes' => 'SYSADMIN: [REDACTED]',
        'os' => '[REDACTED]',
        'ip' => random_ip(),
        'network' => 1,
        'level_id' => 6,
        'created_at' => timestamp("1923-03-09 06:30:00", true)
    ],
];