<?php

return [
    [
        'id' => 1,
        'user_id' => 1,
        'hostname' => 'defcom-net', 
        'password' => random_pass(),
        'org' => 'Defense & Communications Network',
        'location' => '',
        'welcome' => 'Authorized users only!',
        'notes' => 'SYSADMIN: admin@defcom',
        'os' => 'IDM Mainframe/VOS',
        'ip' => random_ip(),
        'network' => 1,
        'level_id' => 1,
        'created_at' => timestamp("1969-10-30 06:30:00", true)
    ],
    [
        'id' => 2,
        'user_id' => 1,
        'hostname' => 'defcom', 
        'password' => random_pass(),
        'org' => 'Defense & Communications Industries',
        'location' => 'Washington D.C., USA',
        'welcome' => 'Welcome to DefCom Industries',
        'notes' => 'SYSADMIN: admin@defcom',
        'os' => 'IDM Mainframe/VOS',
        'ip' => random_ip(),
        'network' => 1,
        'level_id' => 1,
        'created_at' => timestamp("1949-10-30 06:30:00", true)
    ],
    [
        'id' => 3,
        'user_id' => 1,
        'hostname' => 'syscorp', 
        'password' => random_pass(),
        'org' => 'Systems Corporation (Syndicate)',
        'location' => 'Cheyenne Mountain, Colorado, USA',
        'welcome' => 'Welcome to The Syndicate',
        'notes' => 'SYSADMIN: admin@syscorp',
        'os' => 'IDM Mainframe/VOS',
        'ip' => random_ip(),
        'network' => 1,
        'level_id' => 1,
        'created_at' => timestamp("1948-10-30 06:30:00", true)
    ],
    [
        'id' => 4,
        'user_id' => 1,
        'hostname' => 'vault0', 
        'password' => random_pass(),
        'org' => 'Vault Security Corp. (Vault-Sec)',
        'location' => 'Cheyenne Mountain, Colorado, USA',
        'welcome' => 'Welcome to The Syndicate',
        'notes' => 'SYSADMIN: admin@syscorp',
        'os' => 'IDM Mainframe/VOS',
        'ip' => random_ip(),
        'network' => 1,
        'level_id' => 1,
        'created_at' => timestamp("1931-10-30 06:30:00", true)
    ],
    [
        'id' => 5,
        'user_id' => 1,
        'hostname' => 'vault0', 
        'password' => random_pass(),
        'org' => 'Vault Security Corp. (Vault-Sec)',
        'location' => 'Cheyenne Mountain, Colorado, USA',
        'welcome' => 'Welcome to The Syndicate',
        'notes' => 'SYSADMIN: admin@syscorp',
        'os' => 'IDM Mainframe/VOS',
        'ip' => random_ip(),
        'network' => 1,
        'level_id' => 1,
        'created_at' => timestamp("1931-10-30 06:30:00", true)
    ],
];