<?php

return [
    [
        'id' => 1,
        'user_id' => 1,
        'hostname' => 'IDM.NET', 
        'password' => word_pass(),
        'org' => 'IDM NETWORK (IDM)',
        'location' => 'ARMON, NEW YORK, USA',
        'welcome' => 'WELCOME TO IDM CORP. NETWORK',
        'notes' => 'SYSADMIN: ADMIN@IDM.NET',
        'os' => 'SU/DOS V1.10',
        'ip' => random_ip(),
        'is_network' => 1,
        'credits' => 0,
        'level' => 2,
        'created_at' => timestamp("1911-06-16 06:30:00", true)
    ],
    [
        'id' => 2,
        'user_id' => 1,
        'hostname' => 'IDM.COM', 
        'password' => word_pass(),
        'org' => 'INTERNATIONAL DATA MACHINES CORP. (IDM)',
        'location' => 'ARMON, NEW YORK, USA',
        'welcome' => 'WELCOME TO IDM CORP.',
        'notes' => 'SYSADMIN: ADMIN@IDM.COM',
        'os' => 'SU/DOS V1.10',
        'ip' => random_ip(),
        'is_network' => 0,
        'credits' => 5,
        'level' => 3,
        'created_at' => timestamp("1911-06-16 06:30:00", true)
    ],
    [
        'id' => 3,
        'user_id' => 1,
        'hostname' => 'GEC.NET', 
        'password' => word_pass(),
        'org' => 'GEC NETWORK (GEC)',
        'location' => 'SAN RAMON, CALIFORNIA, USA',
        'welcome' => 'WELCOME TO GEC CORP.',
        'notes' => 'SYSADMIN: ADMIN@GEC.NET',
        'os' => 'SU/DOS V3.0',
        'ip' => random_ip(),
        'is_network' => 1,
        'credits' => 15,
        'level' => 4,
        'created_at' => timestamp("1892-04-30 06:30:00", true)
    ],
    [
        'id' => 4,
        'user_id' => 1,
        'hostname' => 'GEC.COM', 
        'password' => word_pass(),
        'org' => 'GENERAL ENERGY & COMMUNICATION CORP. (GEC)',
        'location' => 'SAN RAMON, CALIFORNIA, USA',
        'welcome' => 'WELCOME TO GEC CORP.',
        'notes' => 'SYSADMIN: ADMIN@GEC.COM',
        'os' => 'SU/DOS V3.0',
        'ip' => random_ip(),
        'is_network' => 0,
        'credits' => 15,
        'level' => 5,
        'created_at' => timestamp("1892-04-30 06:30:00", true)
    ],
    [
        'id' => 5,
        'user_id' => 1,
        'hostname' => 'DFC.NET', 
        'password' => word_pass(),
        'org' => 'DEFCON NETWORK (DFC)',
        'location' => 'AREA 51, NEVADA, USA',
        'welcome' => 'WELCOME TO DEFCON CORP. NETWORK',
        'notes' => 'SYSADMIN: ADMIN@DFC.NET',
        'os' => 'SU/DOS V4.0',
        'ip' => random_ip(),
        'is_network' => 1,
        'credits' => 15,
        'level' => 6,
        'created_at' => timestamp("1958-10-30 06:30:00", true)
    ],
    [
        'id' => 6,
        'user_id' => 1,
        'hostname' => 'DFC.COM', 
        'password' => word_pass(),
        'org' => 'DEFENSE & CONTROL CORP. (DFC)',
        'location' => 'LOS ANGELES, CALIFORNIA, USA',
        'welcome' => 'WELCOME TO DEFCON CORP.',
        'notes' => 'SYSADMIN: ADMIN@DFC.COM',
        'os' => 'SU/DOS V4.0',
        'ip' => random_ip(),
        'is_network' => 0,
        'credits' => 50,
        'level' => 7,
        'created_at' => timestamp("1958-10-30 06:30:00", true)
    ],
    [
        'id' => 7,
        'user_id' => 1,
        'hostname' => 'DFC.MIL', 
        'password' => word_pass(),
        'org' => 'DEFENSE & CONTROL - MILITARY COMMAND (DFC)',
        'location' => 'CMOC, COLORADO, USA',
        'welcome' => 'WELCOME TO DEFCON MILITARY COMMAND',
        'notes' => 'SYSADMIN: ADMIN@DFC.MIL',
        'os' => 'SU/DOS V4.0',
        'ip' => random_ip(),
        'is_network' => 0,
        'credits' => 100,
        'level' => 8,
        'created_at' => timestamp("1958-10-30 06:30:00", true)
    ],
    [
        'id' => 8,
        'user_id' => 1,
        'hostname' => 'SCS.NET', 
        'password' => word_pass(),
        'org' => 'SYSCORP NETWORK (SCS)',
        'location' => 'NEW YORK, USA',
        'welcome' => 'WELCOME TO THE SYSCORP NETWORK',
        'notes' => 'SYSADMIN: ADMIN@SCS.NET',
        'os' => 'SU/DOS V3.0',
        'ip' => random_ip(),
        'is_network' => 1,
        'credits' => 15,
        'level' => 9,
        'created_at' => timestamp("1950-01-30 06:30:00", true)
    ],
    [
        'id' => 9,
        'user_id' => 1,
        'hostname' => 'SCS.COM', 
        'password' => word_pass(),
        'org' => 'SYSCORP SYSTEMS (SCS)',
        'location' => 'NEW YORK, USA',
        'welcome' => 'WELCOME TO SYSCORP SYSTEMS',
        'notes' => 'SYSADMIN: ADMIN@SCS.COM',
        'os' => 'SU/DOS V3.0',
        'ip' => random_ip(),
        'is_network' => 0,
        'credits' => 50,
        'level' => 10,
        'created_at' => timestamp("1950-01-30 06:30:00", true)
    ],
    [
        'id' => 10,
        'user_id' => 1,
        'hostname' => 'SCS.EDU', 
        'password' => word_pass(),
        'org' => 'SYSCORP EDUCATION (SCS)',
        'location' => 'LBNL, CALIFORNIA, USA',
        'welcome' => 'WELCOME TO SYSCORP EDUCATION',
        'notes' => 'SYSADMIN: ADMIN@SCS.EDU',
        'os' => 'SU/DOS V1.10',
        'ip' => random_ip(),
        'is_network' => 0,
        'credits' => 5,
        'level' => 11,
        'created_at' => timestamp("1984-01-30 06:30:00", true)
    ],
    [
        'id' => 11,
        'user_id' => 1,
        'hostname' => 'SCS.GOV', 
        'password' => word_pass(),
        'org' => 'SYSCORP SYNDICATE (SCS)',
        'location' => 'WHITE HOUSE, Washington DC, USA',
        'welcome' => 'WELCOME TO THE SYNDICATE.',
        'notes' => 'SYSADMIN: ADMIN@SCS.GOV',
        'os' => 'SU/DOS V3.0',
        'ip' => random_ip(),
        'is_network' => 0,
        'credits' => 75,
        'level' => 12,
        'created_at' => timestamp("1950-01-30 06:30:00", true)
    ],
    [
        'id' => 12,
        'user_id' => 0,
        'hostname' => 'FALLOUT.ORG', 
        'password' => word_pass(),
        'org' => 'THE FALL OUTCASTS CHAOS COMPUTER CLUB (FALLOUT)',
        'location' => 'HANNOVER, GERMANY',
        'welcome' => 'WELCOME TO THE OPEN LEGACY-NET, FELLOW OUTCASTS! F*CK (AND HACK) ALL COMPANIES!',
        'notes' => 'SYSADMIN: ADMIN@FALLOUT.ORG',
        'os' => '4.3 BSD VAX-11/780',
        'ip' => random_ip(),
        'is_network' => 0,
        'credits' => 100,
        'level' => 15,
        'created_at' => timestamp("1975-01-30 06:30:00", true)
    ],
];